---
apiVersion: v1
kind: Service
metadata:
  name: mangos-mysql
  namespace: wotlk
  labels:
    app: mangos-mysql
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    app: mangos-mysql
  type: NodePort